name: Deploy to GCP VM

# Trigger this pipeline only when someone pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Pull your repository code onto the GitHub virtual runner
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Open an SSH connection to your GCP VM and execute build commands
    - name: Executing remote SSH commands to deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_SSH_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        port: 22
        script: |
                  # Go to the home directory of the github-actions user
                  cd ~
                  
                  # If the repo hasn't been cloned by this user yet, clone it
                  if [ ! -d "react_fastapi_boilerplate" ]; then
                    git clone https://github.com/aagirre92/react_fastapi_boilerplate.git
                  fi
                  
                  # Navigate into the folder
                  cd react_fastapi_boilerplate
                  
                  # Pull the latest code
                  git pull origin main
                  
                  # Tear down existing containers and rebuild
                  sudo docker-compose down
                  sudo docker-compose up -d --build